import { FormData } from '../types';

// Helper to get a date in the current month for birthday testing
const getCurrentMonthBirthday = () => {
  const today = new Date();
  const year = 1990; // a fixed year
  const month = today.getMonth();
  const day = Math.max(1, Math.min(28, today.getDate())); // to avoid month-end issues
  return new Date(year, month, day).toISOString().split('T')[0];
}

const getTerminationDateCurrentMonth = () => {
    const today = new Date();
    return new Date(today.getFullYear(), today.getMonth(), 15).toISOString().split('T')[0];
}


export const mockPJData: FormData[] = [
  {
    razaoSocial: 'Tech Solutions Ltda.',
    nomeFantasia: 'Tech Solutions',
    cnpj: '11.222.333/0001-44',
    inscricaoEstadual: '123.456.789.112',
    enderecoComercial: 'Rua da Tecnologia, 123',
    cidade: 'São Paulo',
    uf: 'SP',
    cep: '01000-000',
    telefoneComercial: '(11) 98765-4321',
    emailContato: 'contato@techsolutions.com',
    responsavelNomeCompleto: 'Ana Silva',
    responsavelCpf: '111.222.333-44',
    dataNascimento: '1988-07-25',
    responsavelCargo: 'Desenvolvedora Sênior',
    responsavelCelular: '(11) 91111-2222',
    responsavelEmail: 'ana.silva@email.com',
    banco: '341 - Itaú Unibanco S.A.',
    agencia: '0001',
    conta: '12345-6',
    tipoConta: 'pj',
    titularConta: 'Tech Solutions Ltda.',
    dataInicio: new Date().toISOString().split('T')[0], // Hired this month
    gestorDireto: 'Carlos Pereira',
    areaProjeto: 'Projeto Phoenix',
    centroCusto: 'Tecnologia - P&D',
    valorMensal: '12000',
    formaPagamento: 'transferencia',
    formaPagamentoOutro: '',
    dataLimiteNF: new Date().toISOString().split('T')[0],
    dataPrevistaPagamento: new Date(new Date().setDate(new Date().getDate() + 350)).toISOString().split('T')[0],
    dataFim: null,
    daysOffRestantes: 8,
    historicoReajustes: [
        { data: '2023-08-01', valorAnterior: '10000', novoValor: '12000', motivo: 'Reajuste anual' }
    ],
    documentos: [],
    declaracao: true,
  },
  {
    razaoSocial: 'Creative Minds EIRELI',
    nomeFantasia: 'Creative Minds',
    cnpj: '44.555.666/0001-77',
    inscricaoEstadual: 'Isento',
    enderecoComercial: 'Avenida da Inovação, 456',
    cidade: 'Rio de Janeiro',
    uf: 'RJ',
    cep: '20000-000',
    telefoneComercial: '(21) 97654-3210',
    emailContato: 'contato@creativeminds.com',
    responsavelNomeCompleto: 'Bruno Costa',
    responsavelCpf: '222.333.444-55',
    dataNascimento: getCurrentMonthBirthday(), // Birthday this month
    responsavelCargo: 'UX/UI Designer',
    responsavelCelular: '(21) 92222-3333',
    responsavelEmail: 'bruno.costa@email.com',
    banco: '237 - Bradesco S.A.',
    agencia: '0002',
    conta: '54321-0',
    tipoConta: 'pj',
    titularConta: 'Creative Minds EIRELI',
    dataInicio: '2022-03-01',
    gestorDireto: 'Fernanda Lima',
    areaProjeto: 'App Mobile de Varejo',
    centroCusto: 'Produto - Varejo Digital',
    valorMensal: '9500',
    formaPagamento: 'pix',
    formaPagamentoOutro: '',
    dataLimiteNF: new Date().toISOString().split('T')[0],
    dataPrevistaPagamento: new Date(new Date().setDate(new Date().getDate() + 25)).toISOString().split('T')[0],
    dataFim: null,
    daysOffRestantes: 12,
    documentos: [],
    declaracao: true,
  },
  {
    razaoSocial: 'Data Analytics ME',
    nomeFantasia: 'Data Analytics',
    cnpj: '77.888.999/0001-00',
    inscricaoEstadual: '987.654.321.987',
    enderecoComercial: 'Praça dos Dados, 789',
    cidade: 'Belo Horizonte',
    uf: 'MG',
    cep: '30000-000',
    telefoneComercial: '(31) 96543-2109',
    emailContato: 'contato@dataanalytics.com',
    responsavelNomeCompleto: 'Mariana Oliveira',
    responsavelCpf: '333.444.555-66',
    dataNascimento: '1995-02-14',
    responsavelCargo: 'Analista de Dados',
    responsavelCelular: '(31) 93333-4444',
    responsavelEmail: 'mariana.oliveira@email.com',
    banco: '001 - Banco do Brasil S.A.',
    agencia: '0003',
    conta: '67890-1',
    tipoConta: 'corrente',
    titularConta: 'Mariana Oliveira',
    dataInicio: '2024-01-10',
    gestorDireto: 'Carlos Pereira',
    areaProjeto: 'BI Dashboard',
    centroCusto: 'Inteligência de Mercado',
    valorMensal: '10500',
    formaPagamento: 'transferencia',
    formaPagamentoOutro: '',
    dataLimiteNF: new Date().toISOString().split('T')[0],
    dataPrevistaPagamento: new Date(new Date().setDate(new Date().getDate() + 80)).toISOString().split('T')[0],
    dataFim: getTerminationDateCurrentMonth(), // Terminated this month
    daysOffRestantes: 5,
    historicoReajustes: [
        { data: '2024-06-01', valorAnterior: '10000', novoValor: '10500', motivo: 'Ajuste de escopo' }
    ],
    documentos: [],
    declaracao: true,
  },
    {
    razaoSocial: 'Cloud Services Inc.',
    nomeFantasia: 'Cloud Services',
    cnpj: '12.345.678/0001-99',
    inscricaoEstadual: 'Isento',
    enderecoComercial: 'Alameda dos SREs, 100',
    cidade: 'Curitiba',
    uf: 'PR',
    cep: '80000-000',
    telefoneComercial: '(41) 99999-8888',
    emailContato: 'contato@cloudservices.com',
    responsavelNomeCompleto: 'Rafael Souza',
    responsavelCpf: '444.555.666-77',
    dataNascimento: '1982-11-30',
    responsavelCargo: 'Engenheiro DevOps',
    responsavelCelular: '(41) 94444-5555',
    responsavelEmail: 'rafael.souza@email.com',
    banco: '260 - Nu Pagamentos S.A.',
    agencia: '0001',
    conta: '98765-4',
    tipoConta: 'digital',
    titularConta: 'Rafael Souza',
    dataInicio: '2021-06-20',
    gestorDireto: 'Juliana Martins',
    areaProjeto: 'Infraestrutura Cloud',
    centroCusto: 'Operações - Infra',
    valorMensal: '15000',
    formaPagamento: 'pix',
    formaPagamentoOutro: '',
    dataLimiteNF: new Date().toISOString().split('T')[0],
    dataPrevistaPagamento: new Date(new Date().setDate(new Date().getDate() + 120)).toISOString().split('T')[0],
    dataFim: '2023-12-31', // Already terminated
    daysOffRestantes: 0,
    documentos: [],
    declaracao: true,
  },
];